mnemonic: sight flat tattoo gap canal enforce ugly tomorrow level weekend gossip suspect walnut frozen stable
seed:
password:
OperatorAccountID: "0.0.9201078"
OperatorPrivateKey: "1b12d89d7e8f714b29034dc6e976b5ce2d50174d5716ccb32e5498344a9892fb"
ChainType: "mainnet"  # or "testnet"
