// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0-devel
// 	protoc        v3.6.1
// source: hdwallet.proto

package hdwallet

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageTypeEnum int32

const (
	MessageTypeEnum_Generate      MessageTypeEnum = 0
	MessageTypeEnum_Encrypt       MessageTypeEnum = 1
	MessageTypeEnum_Decrypt       MessageTypeEnum = 2
	MessageTypeEnum_Unlock        MessageTypeEnum = 3
	MessageTypeEnum_Error         MessageTypeEnum = 100
	MessageTypeEnum_Message       MessageTypeEnum = 101
	MessageTypeEnum_TextInput     MessageTypeEnum = 102
	MessageTypeEnum_PasswordInput MessageTypeEnum = 103
	MessageTypeEnum_File          MessageTypeEnum = 104
	MessageTypeEnum_Done          MessageTypeEnum = 200
	MessageTypeEnum_Ping          MessageTypeEnum = 999
	MessageTypeEnum_Pong          MessageTypeEnum = 1000
	MessageTypeEnum_Unknown       MessageTypeEnum = -1
)

// Enum value maps for MessageTypeEnum.
var (
	MessageTypeEnum_name = map[int32]string{
		0:    "Generate",
		1:    "Encrypt",
		2:    "Decrypt",
		3:    "Unlock",
		100:  "Error",
		101:  "Message",
		102:  "TextInput",
		103:  "PasswordInput",
		104:  "File",
		200:  "Done",
		999:  "Ping",
		1000: "Pong",
		-1:   "Unknown",
	}
	MessageTypeEnum_value = map[string]int32{
		"Generate":      0,
		"Encrypt":       1,
		"Decrypt":       2,
		"Unlock":        3,
		"Error":         100,
		"Message":       101,
		"TextInput":     102,
		"PasswordInput": 103,
		"File":          104,
		"Done":          200,
		"Ping":          999,
		"Pong":          1000,
		"Unknown":       -1,
	}
)

func (x MessageTypeEnum) Enum() *MessageTypeEnum {
	p := new(MessageTypeEnum)
	*p = x
	return p
}

func (x MessageTypeEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageTypeEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_hdwallet_proto_enumTypes[0].Descriptor()
}

func (MessageTypeEnum) Type() protoreflect.EnumType {
	return &file_hdwallet_proto_enumTypes[0]
}

func (x MessageTypeEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageTypeEnum.Descriptor instead.
func (MessageTypeEnum) EnumDescriptor() ([]byte, []int) {
	return file_hdwallet_proto_rawDescGZIP(), []int{0}
}

type Body struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type    MessageTypeEnum `protobuf:"varint,1,opt,name=type,proto3,enum=rpc.MessageTypeEnum" json:"type,omitempty"`
	Args    []string        `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	Message string          `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Data    []byte          `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Body) Reset() {
	*x = Body{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hdwallet_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Body) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Body) ProtoMessage() {}

func (x *Body) ProtoReflect() protoreflect.Message {
	mi := &file_hdwallet_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Body.ProtoReflect.Descriptor instead.
func (*Body) Descriptor() ([]byte, []int) {
	return file_hdwallet_proto_rawDescGZIP(), []int{0}
}

func (x *Body) GetType() MessageTypeEnum {
	if x != nil {
		return x.Type
	}
	return MessageTypeEnum_Generate
}

func (x *Body) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *Body) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Body) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_hdwallet_proto protoreflect.FileDescriptor

var file_hdwallet_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x68, 0x64, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x03, 0x72, 0x70, 0x63, 0x22, 0x72, 0x0a, 0x04, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x28, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x72, 0x70,
	0x63, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x45, 0x6e, 0x75,
	0x6d, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x61, 0x72, 0x67, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x2a, 0xc0, 0x01, 0x0a, 0x0f, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x45, 0x6e, 0x75, 0x6d, 0x12, 0x0c, 0x0a,
	0x08, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x45,
	0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x44, 0x65, 0x63, 0x72,
	0x79, 0x70, 0x74, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x55, 0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x10,
	0x03, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x10, 0x64, 0x12, 0x0b, 0x0a, 0x07,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x10, 0x65, 0x12, 0x0d, 0x0a, 0x09, 0x54, 0x65, 0x78,
	0x74, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x10, 0x66, 0x12, 0x11, 0x0a, 0x0d, 0x50, 0x61, 0x73, 0x73,
	0x77, 0x6f, 0x72, 0x64, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x10, 0x67, 0x12, 0x08, 0x0a, 0x04, 0x46,
	0x69, 0x6c, 0x65, 0x10, 0x68, 0x12, 0x09, 0x0a, 0x04, 0x44, 0x6f, 0x6e, 0x65, 0x10, 0xc8, 0x01,
	0x12, 0x09, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x10, 0xe7, 0x07, 0x12, 0x09, 0x0a, 0x04, 0x50,
	0x6f, 0x6e, 0x67, 0x10, 0xe8, 0x07, 0x12, 0x14, 0x0a, 0x07, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77,
	0x6e, 0x10, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x01, 0x32, 0x2f, 0x0a, 0x08,
	0x48, 0x64, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x12, 0x23, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x12, 0x09, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x42, 0x6f, 0x64, 0x79, 0x1a, 0x09,
	0x2e, 0x72, 0x70, 0x63, 0x2e, 0x42, 0x6f, 0x64, 0x79, 0x28, 0x01, 0x30, 0x01, 0x42, 0x2d, 0x5a,
	0x2b, 0x67, 0x69, 0x74, 0x2e, 0x64, 0x65, 0x76, 0x62, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x68, 0x64, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_hdwallet_proto_rawDescOnce sync.Once
	file_hdwallet_proto_rawDescData = file_hdwallet_proto_rawDesc
)

func file_hdwallet_proto_rawDescGZIP() []byte {
	file_hdwallet_proto_rawDescOnce.Do(func() {
		file_hdwallet_proto_rawDescData = protoimpl.X.CompressGZIP(file_hdwallet_proto_rawDescData)
	})
	return file_hdwallet_proto_rawDescData
}

var file_hdwallet_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_hdwallet_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_hdwallet_proto_goTypes = []interface{}{
	(MessageTypeEnum)(0), // 0: rpc.MessageTypeEnum
	(*Body)(nil),         // 1: rpc.Body
}
var file_hdwallet_proto_depIdxs = []int32{
	0, // 0: rpc.Body.type:type_name -> rpc.MessageTypeEnum
	1, // 1: rpc.HdWallet.Command:input_type -> rpc.Body
	1, // 2: rpc.HdWallet.Command:output_type -> rpc.Body
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_hdwallet_proto_init() }
func file_hdwallet_proto_init() {
	if File_hdwallet_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_hdwallet_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Body); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_hdwallet_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hdwallet_proto_goTypes,
		DependencyIndexes: file_hdwallet_proto_depIdxs,
		EnumInfos:         file_hdwallet_proto_enumTypes,
		MessageInfos:      file_hdwallet_proto_msgTypes,
	}.Build()
	File_hdwallet_proto = out.File
	file_hdwallet_proto_rawDesc = nil
	file_hdwallet_proto_goTypes = nil
	file_hdwallet_proto_depIdxs = nil
}
